crestroncip:
  ip: crestron_host_ip like 192.168.1.1
  port: cip port default 41794
  ipid: cip ip_ip like 0x03

switch:
  - platform: crestroncip
    name: "test_sw1"
    switch_on_digital: 1
    switch_off_digital: 2
    switch_fb_digital: 1
    type: switch
  - platform: crestroncip
    name: "test_sw2"
    switch_on_digital: 3
    switch_off_digital: 4
    switch_fb_digital: 3
    type: switch
light:
  - platform: crestroncip
    name: "test_sw_light"
    switch_on_digital: 5
    switch_off_digital: 6
    switch_fb_digital: 5
    type: switch
  - platform: crestroncip
    name: "test_dimmer_light"
    brightness_analog: 7
    brightness_fb_analog: 7
    type: brightness
  - platform: crestroncip
    name: "test_ct_light"
    brightness_analog: 8
    brightness_fb_analog: 8
    color_temp_analog: 9
    color_temp_fb_analog: 9
    color_temp_max: 6500
    color_temp_min: 2700
    type: color_temp
cover:
  - platform: crestroncip
    name: test_open_close_cover1
    type: open_close
    open_digital: 10
    close_digital: 11
    stop_digital: 12
    is_closed_fb_digital: 10
  - platform: crestroncip
    name: test_position_cover2
    type: position
    open_digital: 13
    close_digital: 14
    stop_digital: 15
    is_closed_fb_digital: 13
    position_analog: 14
    position_fb_analog: 14
climate:
  - platform: crestroncip
    name: test_hvac
    type: AC
    ac_power_on_digital: 22
    ac_power_off_digital: 23
    ac_mode_analog: 22
    ac_mode_fb_analog: 22
    ac_set_temp_analog: 23
    ac_set_temp_fb_analog: 23
    ac_current_temp_fb_analog: 24
    ac_fan_mode_analog: 25
    ac_fan_mode_fb_analog: 25
    ac_max_temp: 35
    ac_min_temp: 15
    ac_temp_step: 1
